### ISSUE TITLE
1.0.17 SpambotMod triggers error in Contao 4.9.12

### ISSUE THREAD

**Issue by wuapaadev** [syncgw/contao-spambot#1]
Hi syncgw,

I'm getting an error when running spambot 1.0.17 with Contao 4.9.12

`request.CRITICAL: Uncaught PHP Exception TypeError: "Return value of syncgw\SpamBotBundle\Module\SpamBotMod::replaceInsertTag() must be of the type string, bool returned" at /data/develop/bcdev.wuapaa.at/vendor/syncgw/contao-spambot/src/Module/SpamBotMod.php line 59 {"exception":"[object] (TypeError(code: 0): Return value of syncgw\\SpamBotBundle\\Module\\SpamBotMod::replaceInsertTag() must be of the type string, bool returned at /data/develop/bcdev.wuapaa.at/vendor/syncgw/contao-spambot/src/Module/SpamBotMod.php:59)"} []
`

Modifiing Line 59 in SpambotMod.php to `return '' ` resolves that issue for me, but I'm not sure if this leads to other issues..

Regards,

**Comment by syncgw** [comment]
Thank you for reporting. Fixed in 1.0.18.

**Comment by wuapaadev** [comment]
Wow, that was fast :-D

Thanks for fixing it - and for the nice plugin, of course!

Regards

**Comment by wuapaadev** [comment]
Update - tried 1.0.18  on another C4 Installation - the problem still exists.
 (I think I've forgotten to revert my changes on the initial  installation)

**Comment by syncgw** [comment]
Contao Controller.php:795 `* @return string The text with the replaced tags`
SpamBotMod.php:54 `public function replaceInsertTag(string $strTag): string`

That's my installation.

**Comment by wuapaadev** [comment]
I'm not sure, I'm not an advanced PHP-Programmer,  but: 

In SpamBotMod.php:

Line 59 will return NULL not an empty String
also Line 65 (if false)

or is there any "PHP-Magic" involved?

**Comment by wuapaadev** [comment]
Ah well - digging a bit further...

replaceInsertTag shoud return string|false  -> so release 1.0.17 where the right return values; but the function return value shoul d not be typed as ":string"

See like in https://github.com/contao/contao/blob/991282912ef0c590b92d25b67785463516a38890/news-bundle/src/EventListener/InsertTagsListener.php#L47

**Comment by syncgw** [comment]
What you're referring to is the news-package. `replaceInsertTag()` always returns a string. For sake of conformity, I changed NULL to '' (which should be the same). -> 1.0.19

**Comment by wuapaadev** [comment]
Many Thanks syncgw!
